### PR TITLE
Sample app to test the product with the license manager

### PR DESCRIPTION
**Pull request by sadhasivam-ladybirdweb**
### Fixes
- Fixes [#164](https://github.com/ladybirdweb/agora-license-manager/issues/164)

## Running Migrations and Seeders

To set up your database schema and seed it with initial data, you need to run the following Artisan commands:

```bash
php artisan migrate
php artisan db:seed

### CODE REVIEW

**Comment by sandesh556** [comment]
A doc needs to be created on wiki on how to install this product

**Comment by indira15v** [comment]
@sadhasivam-ladybirdweb please get code approval

**Comment by indira15v** [comment]
**Testing summary**
Tested the PR updated issues and need some clarifications 
Issue  sheet :https://docs.google.com/spreadsheets/d/1kXty4cKr2HIlZMXtFrQ_LpGVi1TDmzv8D4f8qszeqek/edit?gid=0#gid=0

**Comment by indira15v** [comment]
**Testing summary**
Tested the PR updated issues and please get code approval
Total issues :18
Issue sheet :https://docs.google.com/spreadsheets/d/1kXty4cKr2HIlZMXtFrQ_LpGVi1TDmzv8D4f8qszeqek/edit?gid=0#gid=0

**Comment by AbishekChinnaraju** [comment]
@sadhasivam-ladybirdweb  please get code approval

**Comment by indira15v** [comment]
Need some clarifications from developer side so keeping on hold

**Comment by AbishekChinnaraju** [comment]
We've put this PR on hold due to other high-priority PRs in Faveo.

**Review by RafficMohammed — APPROVED** [review]

**Review by sandesh556 — APPROVED** [review]

**Comment by indira15v** [comment]
Round one testing summary
Note
1.In user local path when we give random value also receiving the correct response 
2.When we generate the parametres value once then if  try to click the same no API response was happening 
These two things needs to be fixed if done,will approve PR

**Comment by sadhasivam-ladybirdweb** [comment]
@indira15v 
1. For testing APIs, we don’t need any validation on the parameters; this is not a form.
2. I’ll add a loader to show that it’s requesting the parameters.

**Comment by AbishekChinnaraju** [comment]
**Round Two testing summary:**
I tested this PR in my local fresh installation.
Total testing time: 1.5 days
**Note:** 
- The mentioned issues in the sheet are fixed and working fine.
- Now the responses are shown as per the given Parameters.

**Review by AbishekChinnaraju — APPROVED** [review]

**Comment by indira15v** [comment]
Round one retesting summary
Tested this PR in local with fresh 
Testing time : 1.5 days
Issue sheet:
https://docs.google.com/spreadsheets/d/1kXty4cKr2HIlZMXtFrQ_LpGVi1TDmzv8D4f8qszeqek/edit?gid=0#gid=0
The mentioned issues in the sheet are fixed and working fine.
Note :
Created separate issue in license manager while testing this PR 
https://github.com/ladybirdweb/agora-license-manager/issues/291

**Review by indira15v — APPROVED** [review]

**Pull request merged**
